### PR TITLE
Fixed isJDK_N_OrHigher method for Java 10 or higher version.

### PR DESCRIPTION
**Pull request by gaurav072**
I have fixed the issue raised by myself for Java 10  compatibility. Could you please review the changes and merge it.

https://github.com/audit4j/audit4j-core/issues/82

### CODE REVIEW

**Comment by taitopilvipete** [comment]
@janithb +1 for this: we're upgrading applications to Java 11 and facing this same issue. Could this be merged?

**Comment by gaurav072** [comment]
Merge request compatible up to java 11.

**Comment by bcaure** [comment]
+1 : can you merge, it's a blocker!

**Comment by bcaure** [comment]
unfortunately it does not work for jdk 9! jdk 9 versions starts with 9.x

**Comment by gaurav072** [comment]
But JDK 9 is no longer available by Oracle.

**Comment by wuchaosuperfive** [comment]
when is this fix going to be officially released?

**Comment by BartBM** [comment]
Could this be released please?

**Pull request merged**
